spring.application.name=workflow-engine
server.port=8080

# Default: H2 in-memory (works out of the box, no MySQL needed)
spring.datasource.url=jdbc:h2:mem:workflowdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Static files
spring.web.resources.static-locations=classpath:/static/

logging.level.com.halleyx=INFO
